language: swift

branches:
 only:
 - master

xcode_project: CollapsibleTable.xcodeproj
xcode_scheme: CollapsibleTable
osx_image: xcode9
xcode_sdk: iphonesimulator11.0

script: 
 - xcodebuild -scheme CollapsibleTable -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.0' test
 - xcodebuild -scheme CollapsibleTableDemo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.0' test
 